#!/usr/bin/env python3
"""
Demo Script — Shows all 6 products in action
Run this to see what each bot does
"""

print("=" * 60)
print("🚀 NOVA'S BOT STORE — LIVE DEMO")
print("=" * 60)

# Demo 1: Discord Bot
print("\n🎮 DISCORD MODERATION BOT ($200)")
print("-" * 40)
print("Simulated activity:")
print("  [12:34:05] New user joined: @crypto_trader")
print("  [12:34:06] Bot: 👋 Welcome @crypto_trader!")
print("  [12:45:12] Spam detected from @bot123")
print("  [12:45:13] Bot: 🗑️ Deleted spam message")
print("  [12:45:14] Bot: ⚠️ @bot123 has been muted for 1 hour")
print("  [13:02:33] @admin: !ban @spammer")
print("  [13:02:34] Bot: 🔨 @spammer has been banned")

# Demo 2: Telegram Bot
print("\n✈️ TELEGRAM AUTO-REPLY BOT ($150)")
print("-" * 40)
print("Simulated activity:")
print("  [09:15:22] @new_member joined the group")
print("  [09:15:23] Bot: 🎉 Welcome! Type 'help' for commands")
print("  [09:16:45] @user123: 'price'")
print("  [09:16:46] Bot: 💰 Our pricing:\n         - Basic: $50/mo\n         - Pro: $150/mo")
print("  [09:20:11] @admin: /broadcast Big sale today!")
print("  [09:20:12] Bot: 📢 Broadcast sent to 1,247 members")

# Demo 3: Twitter Bot
print("\n🐦 TWITTER AUTO-POSTER ($250)")
print("-" * 40)
print("Menu interface:")
print("  1. Post now")
print("  2. Schedule post")
print("  3. Post thread")
print("  4. View analytics")
print("  5. Exit")
print("\n  Choice: 2")
print("  Tweet: Launching tomorrow! 🚀")
print("  Schedule for: 2026-02-08 09:00")
print("  ✅ Scheduled for tomorrow 9am")
print("\n  [Next day 09:00:00] ✅ Tweet posted!")
print("  https://twitter.com/user/status/1234567890")

# Demo 4: GitHub Bot
print("\n🐙 GITHUB AUTOMATION BOT ($300)")
print("-" * 40)
print("Running automation...")
print("  🏷️ Auto-labeling issues...")
print("    + Added 'bug' to #42")
print("    + Added 'feature' to #43")
print("    + Added 'docs' to #44")
print("  🧹 Managing stale issues...")
print("    ⚠️ Marked #15 as stale (30 days inactive)")
print("    ✗ Closed #8 (37 days stale)")
print("  🔀 Checking PRs for auto-merge...")
print("    ✓ Auto-merged PR #56 (all checks passed)")
print("  📝 Generating release notes...")
print("    Found 15 commits since last release")
print("    ✓ Generated RELEASE_NOTES.md")

# Demo 5: Social Media Manager
print("\n🌐 SOCIAL MEDIA MANAGER ($500)")
print("-" * 40)
print("Menu interface:")
print("  1. Post now")
print("  2. Schedule post")
print("  3. List scheduled posts")
print("  4. Check & publish scheduled")
print("  5. View analytics")
print("\n  Choice: 1")
print("  Content: Big announcement! 🎉")
print("  Platforms: twitter, telegram, discord")
print("\n  ✅ Published to ALL platforms:")
print("    ✓ twitter: 1234567890")
print("    ✓ telegram: 42")
print("    ✓ discord: 9876543210")
print("\n  📊 Analytics:")
print("    Total posts: 47")
print("    By platform: twitter: 30, telegram: 25, discord: 15")

# Demo 6: API Manager
print("\n🔗 API AUTOMATION MANAGER ($350)")
print("-" * 40)
print("Loading example: ETH Price Alert")
print("  Trigger: API poll every 5 minutes")
print("  Condition: {api_response.ethereum.usd} < 2000")
print("  Action: Send notification")
print("\n  🔄 Polling https://api.coingecko.com...")
print("  Current ETH price: $2,354.67")
print("  ✅ Condition not met (price > $2000)")
print("  ⏰ Next check in 5 minutes...")
print("\n  [Later, price drops...]")
print("  🚨 ALERT: ETH price is $1,987.23")
print("  📱 Notification sent!")

print("\n" + "=" * 60)
print("💰 PRICING SUMMARY")
print("=" * 60)
print("  Discord Bot:           $200")
print("  Telegram Bot:          $150")
print("  Twitter Bot:           $250")
print("  GitHub Bot:            $300")
print("  API Manager:           $350")
print("  Social Media Manager:  $500")
print("  " + "-" * 40)
print("  Total Value:          $1,750")
print("\n  🎁 Bundle Deals:")
print("    Starter (Discord+Telegram): $300 (save $50)")
print("    Complete (all 6):          $1200 (save $550)")
print("\n  📦 Includes: Source code + Setup guide + 30-60 day support")
print("  ⚡ Delivery: Same day")
print("\n  💬 DM me to purchase!")
print("=" * 60)
