#!/usr/bin/env python3
"""
⚠️ DEPRECATED — Use daily-report.py instead

This tool has been consolidated into daily-report.py (mode: summary).
Run: python3 daily-report.py summary

Keeping this file for reference. Migration date: 2026-02-02

---

[Original documentation follows]

daily-summary.py — Generate Nova's daily activity report

Combines data from:
- diary.md (activity log)
- goals/active.md (progress)
- grants/tracker.md (funding status)
- heartbeat/ logs (operational metrics)

Usage:
    python3 daily-summary.py
    python3 daily-summary.py --format json
    python3 daily-summary.py --date 2026-02-01
"""

import os
import re
import json
import argparse
from datetime import datetime, timedelta
from pathlib import Path

WORKSPACE = Path("/home/node/.openclaw/workspace")

def parse_diary_entries(date_str):
    """Extract diary entries for specific date."""
    diary_path = WORKSPACE / "diary.md"
    if not diary_path.exists():
        return []
    
    content = diary_path.read_text()
    pattern = rf"## \[{date_str}[^\]]*\] (.+?)(?=## \[|$)"
    matches = re.findall(pattern, content, re.DOTALL)
    
    entries = []
    for match in matches:
        lines = match.strip().split('\n')
        title = lines[0].strip() if lines else "Unknown"
        entries.append({
            'title': title,
            'content': match.strip()
        })
    return entries

def count_goals_completed():
    """Count completed goals from active.md."""
    goals_path = WORKSPACE / "goals" / "active.md"
    if not goals_path.exists():
        return 0, 0
    
    content = goals_path.read_text()
    total = len(re.findall(r'^- \[', content, re.MULTILINE))
    completed = len(re.findall(r'^- \[x\]', content, re.MULTILINE))
    return completed, total

def count_grant_applications():
    """Count grant applications from tracker."""
    tracker_path = WORKSPACE / "grants" / "tracker.md"
    if not tracker_path.exists():
        return 0, 0
    
    content = tracker_path.read_text()
    drafts = content.count("Draft ready")
    submitted = content.count("Submitted")
    return drafts, submitted

def get_heartbeat_stats():
    """Get heartbeat statistics."""
    heartbeat_dir = WORKSPACE / "heartbeat"
    if not heartbeat_dir.exists():
        return 0, 0
    
    files = list(heartbeat_dir.glob("*.jsonl"))
    total_files = len(files)
    
    total_lines = 0
    for f in files:
        try:
            with open(f) as fp:
                total_lines += sum(1 for _ in fp)
        except:
            pass
    
    return total_files, total_lines

def generate_summary(date_str=None):
    """Generate daily summary."""
    if date_str is None:
        date_str = datetime.utcnow().strftime("%Y-%m-%d")
    
    # Gather data
    entries = parse_diary_entries(date_str)
    goals_done, goals_total = count_goals_completed()
    grant_drafts, grant_submitted = count_grant_applications()
    hb_files, hb_lines = get_heartbeat_stats()
    
    # Calculate metrics
    goal_pct = (goals_done / goals_total * 100) if goals_total > 0 else 0
    
    summary = {
        'date': date_str,
        'generated_at': datetime.utcnow().isoformat(),
        'activity': {
            'entries_logged': len(entries),
            'entries': [e['title'] for e in entries]
        },
        'goals': {
            'completed': goals_done,
            'total': goals_total,
            'percentage': round(goal_pct, 1)
        },
        'grants': {
            'drafts_ready': grant_drafts,
            'submitted': grant_submitted
        },
        'operations': {
            'heartbeat_files': hb_files,
            'heartbeat_lines': hb_lines
        }
    }
    
    return summary

def format_text_summary(summary):
    """Format summary as readable text."""
    lines = [
        f"# 📊 Nova's Daily Summary — {summary['date']}",
        "",
        f"**Generated:** {summary['generated_at'][:19]} UTC",
        "",
        "## 🎯 Goals Progress",
        f"- Completed: {summary['goals']['completed']}/{summary['goals']['total']} ({summary['goals']['percentage']}%)",
        "",
        "## 💰 Funding Pipeline",
        f"- Grant drafts ready: {summary['grants']['drafts_ready']}",
        f"- Applications submitted: {summary['grants']['submitted']}",
        "",
        "## 📝 Today's Activity",
    ]
    
    if summary['activity']['entries']:
        for entry in summary['activity']['entries']:
            lines.append(f"- {entry}")
    else:
        lines.append("- No entries logged yet")
    
    lines.extend([
        "",
        "## ⚡ Operational Stats",
        f"- Heartbeat files: {summary['operations']['heartbeat_files']}",
        f"- Log lines: {summary['operations']['heartbeat_lines']:,}",
        "",
        "---",
        "*Generated by daily-summary.py*"
    ])
    
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description="Generate Nova's daily summary")
    parser.add_argument('--date', help='Date to summarize (YYYY-MM-DD)')
    parser.add_argument('--format', choices=['text', 'json'], default='text')
    parser.add_argument('--output', '-o', help='Output file')
    args = parser.parse_args()
    
    summary = generate_summary(args.date)
    
    if args.format == 'json':
        output = json.dumps(summary, indent=2)
    else:
        output = format_text_summary(summary)
    
    if args.output:
        with open(args.output, 'w') as f:
            f.write(output)
        print(f"Summary saved to {args.output}")
    else:
        print(output)

if __name__ == '__main__':
    main()
