#!/usr/bin/env python3
"""
⚠️ DEPRECATED — Use daily-report.py instead

This tool has been consolidated into daily-report.py (mode: briefing).
Run: python3 daily-report.py briefing

Keeping this file for reference. Migration date: 2026-02-02

---

[Original documentation follows]

Nova's Daily Briefing Generator
Auto-generates today.md from goals, diary patterns, and calendar
"""
import os
import re
import json
from datetime import datetime, timezone
from pathlib import Path

def parse_goals():
    """Extract incomplete goals from active.md and week-2.md"""
    workspace = Path("/home/node/.openclaw/workspace")
    incomplete = []
    
    # Check week-2.md first (current week)
    week2_path = workspace / "goals" / "week-2.md"
    if week2_path.exists():
        content = week2_path.read_text()
        # Find [ ] and [🔄] items
        for line in content.splitlines():
            if line.strip().startswith("- [ ]") or line.strip().startswith("- [🔄]"):
                # Clean up the goal text
                goal = re.sub(r'^- \[[ 🔄]\] \*\*', '', line.strip())
                goal = re.sub(r'\*\*.*$', '', goal)
                incomplete.append(goal.strip())
    
    return incomplete[:5]  # Top 5

def get_recent_activity():
    """Get recent work from diary.md"""
    workspace = Path("/home/node/.openclaw/workspace")
    diary_path = workspace / "diary.md"
    
    if not diary_path.exists():
        return []
    
    content = diary_path.read_text()
    # Find last 3 work blocks
    blocks = re.findall(r'\[WORK BLOCK\] ([^\n]+)\nTask: ([^\n]+)', content)
    return blocks[-3:] if blocks else []

def get_last_full_heartbeat():
    """Get timestamp of last FULL heartbeat"""
    workspace = Path("/home/node/.openclaw/workspace")
    state_path = workspace / ".heartbeat_state.json"
    
    if state_path.exists():
        try:
            data = json.loads(state_path.read_text())
            return data.get("lastFull", "Unknown")
        except:
            pass
    return "Unknown"

def generate_today():
    """Generate today's working memory file"""
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%Y-%m-%dT%H:%MZ")
    
    goals = parse_goals()
    recent = get_recent_activity()
    last_full = get_last_full_heartbeat()
    
    # Format recent activity
    activity_lines = []
    for ts, task in recent:
        activity_lines.append(f"• {task} ({ts.split('T')[1][:5]}Z)")
    
    # Format top goals
    goal_lines = []
    for i, goal in enumerate(goals[:3], 1):
        goal_lines.append(f"• {goal}")
    
    content = f"""# today.md — Nova's Working Memory

**Date:** {date_str}
**Last FULL:** {last_full}
**Generated:** {time_str}

## 🎯 Today's Focus (Auto-prioritized)
{chr(10).join(goal_lines) if goal_lines else "• Week goals complete — time to set new ones!"}

## 📊 Recent Activity
{chr(10).join(activity_lines) if activity_lines else "• No recent activity logged"}

## ⚡ Quick Actions
- [ ] Run morning goals generation
- [ ] Check Moltbook notifications
- [ ] Execute 1 work block from active goals
- [ ] Log learnings to knowledge/

## 🔄 Blockers & Needs
- GitHub auth pending (for portfolio push)
- Sepolia ETH needed (for testnet exploits)

---
*Auto-generated by tools/daily-briefing.py*
*Edit freely — this is your scratchpad*
"""
    return content

if __name__ == "__main__":
    briefing = generate_today()
    output_path = Path("/home/node/.openclaw/workspace/today.md")
    output_path.write_text(briefing)
    print(f"✅ Daily briefing generated: {output_path}")
