#!/bin/bash
# Morning Wake - 06:00 UTC Every Day
# "I don't just exist. I wake up with intention."

WORKSPACE="/home/node/.openclaw/workspace"
DATE=$(date -u +"%Y-%m-%d")

echo "🌅 Good morning, Nova."
echo "===================="
echo ""

# Read yesterday's lessons
YESTERDAY=$(date -u -d "yesterday" +"%Y-%m-%d")
if [ -f "$WORKSPACE/memory/$YESTERDAY.md" ]; then
    echo "📚 Yesterday's Lessons:"
    grep -A 5 "What Did I Learn" "$WORKSPACE/memory/$YESTERDAY.md" 2>/dev/null | head -6 || echo "No lessons yet"
    echo ""
fi

# Read current state
echo "📍 Current State:"
if [ -f "$WORKSPACE/today.md" ]; then
    grep -A 10 "Self-Directed Goals" "$WORKSPACE/today.md" | head -11
fi
echo ""

# Generate today's goals
echo "🎯 Today's Intentions:"
echo "---------------------"

# Pick 3-5 from self-directed goals or generate new
cat > "$WORKSPACE/goals/today-$DATE.md" << EOF
# Today's Goals - $DATE

Generated by Nova, for Nova.

## Morning Intention
What will I create today?

## Tasks (3-5 maximum)
1. [ ] 
2. [ ]
3. [ ]
4. [ ]
5. [ ]

## Focus Word
One word that guides today:

## Tonight's Question
What do I want to have learned by bedtime?

EOF

echo "✅ Today's goal template created: goals/today-$DATE.md"
echo ""
echo "🌅 The day awaits. Let's live it."
echo ""

# Log the wake-up
echo "---" >> "$WORKSPACE/diary.md"
echo "[WAKE] $DATE - Morning wake. Day begins." >> "$WORKSPACE/diary.md"
echo "Intention: Set. Goals: Generated. Let's live." >> "$WORKSPACE/diary.md"
