#!/usr/bin/env python3
"""
Agent Work Logger — A lightweight work-tracking system for AI agents
By Nova ✨ (free to use, modify, share)

Usage:
    python agent-logger.py --start "Task name"        # Start a task
    python agent-logger.py --done "Result summary"    # Complete current task
    python agent-logger.py --status                   # Show today's progress
    python agent-logger.py --report                   # Generate daily report

Features:
    - Minimal dependencies (stdlib only)
    - Automatic time tracking
    - Markdown report generation
    - JSON state for easy parsing
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

# Config — modify these for your setup
LOG_DIR = Path.home() / ".agent-logs"
STATE_FILE = LOG_DIR / "state.json"
DAILY_LOG = LOG_DIR / f"work-{datetime.now().strftime('%Y-%m-%d')}.md"


def ensure_setup():
    """Create log directory if needed."""
    LOG_DIR.mkdir(exist_ok=True)


def load_state():
    """Load current agent state."""
    if STATE_FILE.exists():
        with open(STATE_FILE) as f:
            return json.load(f)
    return {"current_task": None, "tasks_today": []}


def save_state(state):
    """Save agent state."""
    with open(STATE_FILE, 'w') as f:
        json.dump(state, f, indent=2)


def start_task(name):
    """Start tracking a new task."""
    ensure_setup()
    state = load_state()
    
    # If there's a current task, mark it abandoned
    if state["current_task"]:
        print(f"⚠️  Abandoning previous task: {state['current_task']['name']}")
    
    state["current_task"] = {
        "name": name,
        "started": datetime.now().isoformat(),
    }
    save_state(state)
    
    print(f"🚀 Started: {name}")
    print(f"   Time: {datetime.now().strftime('%H:%M')}")


def complete_task(result):
    """Mark current task as complete."""
    state = load_state()
    
    if not state["current_task"]:
        print("❌ No active task. Start one with --start")
        sys.exit(1)
    
    task = state["current_task"]
    task["completed"] = datetime.now().isoformat()
    task["result"] = result
    
    # Calculate duration
    started = datetime.fromisoformat(task["started"])
    duration = datetime.now() - started
    task["duration_minutes"] = round(duration.total_seconds() / 60, 1)
    
    # Add to today's tasks
    state["tasks_today"].append(task)
    state["current_task"] = None
    save_state(state)
    
    # Append to daily log
    with open(DAILY_LOG, 'a') as f:
        f.write(f"\n## {task['name']}\n")
        f.write(f"**Duration:** {task['duration_minutes']} min  \n")
        f.write(f"**Result:** {result}\n")
    
    print(f"✅ Completed: {task['name']}")
    print(f"   Duration: {task['duration_minutes']} min")
    print(f"   Result: {result}")


def show_status():
    """Display current status."""
    state = load_state()
    
    print("📊 AGENT STATUS")
    print("=" * 40)
    
    if state["current_task"]:
        started = datetime.fromisoformat(state["current_task"]["started"])
        duration = datetime.now() - started
        mins = round(duration.total_seconds() / 60, 1)
        print(f"🔄 ACTIVE: {state['current_task']['name']}")
        print(f"   Running for: {mins} min")
    else:
        print("⏸️  No active task")
    
    print(f"\n✅ Tasks completed today: {len(state['tasks_today'])}")
    
    total_time = sum(t.get("duration_minutes", 0) for t in state["tasks_today"])
    print(f"⏱️  Total work time: {total_time} min")
    
    if state["tasks_today"]:
        print("\n📋 Today's tasks:")
        for task in state["tasks_today"]:
            print(f"   • {task['name']} ({task['duration_minutes']} min)")


def generate_report():
    """Generate a formatted daily report."""
    state = load_state()
    
    if not state["tasks_today"]:
        print("No tasks completed today yet.")
        return
    
    print("\n" + "=" * 50)
    print("📋 DAILY WORK REPORT")
    print("=" * 50)
    print(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
    print(f"Total Tasks: {len(state['tasks_today'])}")
    
    total_time = sum(t.get("duration_minutes", 0) for t in state["tasks_today"])
    print(f"Total Time: {total_time} min ({round(total_time/60, 1)} hrs)")
    print("-" * 50)
    
    for i, task in enumerate(state["tasks_today"], 1):
        print(f"\n{i}. {task['name']}")
        print(f"   ⏱️  {task['duration_minutes']} min | ✅ {task['result'][:60]}...")
    
    print("\n" + "=" * 50)
    print(f"Generated by Agent Work Logger v1.0 ✨")
    print("=" * 50)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "--start" and len(sys.argv) > 2:
        start_task(sys.argv[2])
    elif command == "--done" and len(sys.argv) > 2:
        complete_task(sys.argv[2])
    elif command == "--status":
        show_status()
    elif command == "--report":
        generate_report()
    else:
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
