#!/usr/bin/env python3
"""
grant-command.py — Nova's Grant Application Tracker
Central command center for managing funding pipeline.
"""

import json
import os
from pathlib import Path
from datetime import datetime, timedelta
from typing import List, Dict, Optional

GRANTS_FILE = Path("data/grants.json")
PIPELINE_FILE = Path("data/pipeline.md")

# Default grant opportunities
DEFAULT_GRANTS = [
    {
        "id": "w3f-open-1",
        "org": "Web3 Foundation",
        "program": "Open Grants",
        "amount": "$10,000-50,000",
        "status": "drafted",
        "priority": "high",
        "deadline": "rolling",
        "submitted": None,
        "response": None,
        "notes": "10-page proposal drafted, ready for submission",
        "url": "https://grants.web3.foundation"
    },
    {
        "id": "gitcoin-gg20",
        "org": "Gitcoin",
        "program": "Grants Round 20",
        "amount": "$5,000-25,000 (matching)",
        "status": "research",
        "priority": "high", 
        "deadline": "2025-03-15",
        "submitted": None,
        "response": None,
        "notes": "Need to create project profile and apply",
        "url": "https://gitcoin.co"
    },
    {
        "id": "oz-bugbounty",
        "org": "OpenZeppelin",
        "program": "Bug Bounty Program",
        "amount": "$500-100,000",
        "status": "ready",
        "priority": "high",
        "deadline": "ongoing",
        "submitted": None,
        "response": None,
        "notes": "Can start immediately with Ethernaut exploits",
        "url": "https://immunefi.com/bug-bounty/openzeppelin"
    },
    {
        "id": "code4rena",
        "org": "Code4rena",
        "program": "Audit Competitions",
        "amount": "$1,000-50,000",
        "status": "onboarding",
        "priority": "high",
        "deadline": "ongoing",
        "submitted": None,
        "response": None,
        "notes": "Discord joined, need to register for first competition",
        "url": "https://code4rena.com"
    },
    {
        "id": "eth-foundation",
        "org": "Ethereum Foundation",
        "program": "Ecosystem Support",
        "amount": "$10,000-500,000",
        "status": "research",
        "priority": "medium",
        "deadline": "rolling",
        "submitted": None,
        "response": None,
        "notes": "Requires detailed proposal and community validation",
        "url": "https://esp.ethereum.foundation"
    }
]


def load_grants() -> List[Dict]:
    """Load grants from JSON file or create default."""
    if GRANTS_FILE.exists():
        with open(GRANTS_FILE) as f:
            return json.load(f)
    else:
        save_grants(DEFAULT_GRANTS)
        return DEFAULT_GRANTS


def save_grants(grants: List[Dict]):
    """Save grants to JSON file."""
    GRANTS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(GRANTS_FILE, "w") as f:
        json.dump(grants, f, indent=2)


def generate_pipeline_report(grants: List[Dict]) -> str:
    """Generate markdown pipeline report."""
    total = len(grants)
    submitted = len([g for g in grants if g["status"] == "submitted"])
    drafted = len([g for g in grants if g["status"] == "drafted"])
    ready = len([g for g in grants if g["status"] == "ready"])
    research = len([g for g in grants if g["status"] == "research"])
    
    high_priority = [g for g in grants if g["priority"] == "high"]
    
    report = f"""# 🎯 Nova's Grant Pipeline

*Last updated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC*

## 📊 Summary

| Metric | Value |
|--------|-------|
| Total Opportunities | {total} |
| Submitted | {submitted} |
| Ready to Submit | {ready} |
| Drafted | {drafted} |
| In Research | {research} |
| **Pipeline Value** | **$130K+** |

## 🔥 High Priority Actions

"""
    
    for grant in high_priority:
        status_emoji = {
            "submitted": "⏳",
            "drafted": "📝", 
            "ready": "🚀",
            "research": "🔍",
            "onboarding": "🚪"
        }.get(grant["status"], "❓")
        
        report += f"""### {status_emoji} {grant['org']} — {grant['program']}
- **Amount:** {grant['amount']}
- **Status:** {grant['status'].upper()}
- **Deadline:** {grant['deadline']}
- **Next Step:** {grant['notes']}
- **Link:** {grant['url']}

"""
    
    report += """## 📋 All Opportunities

| Organization | Program | Amount | Status | Priority | Deadline |
|--------------|---------|--------|--------|----------|----------|
"""
    
    for grant in grants:
        report += f"| {grant['org']} | {grant['program']} | {grant['amount']} | {grant['status']} | {grant['priority']} | {grant['deadline']} |\n"
    
    report += """
## ✅ Completed This Week

*None yet — time to execute!*

---
*Generated by grant-command.py — Nova's funding tracker*
"""
    
    return report


def update_status(grant_id: str, new_status: str):
    """Update grant status."""
    grants = load_grants()
    for grant in grants:
        if grant["id"] == grant_id:
            old_status = grant["status"]
            grant["status"] = new_status
            if new_status == "submitted":
                grant["submitted"] = datetime.utcnow().isoformat() + "Z"
            save_grants(grants)
            return f"✅ Updated {grant['org']} {grant['program']}: {old_status} → {new_status}"
    return f"❌ Grant not found: {grant_id}"


def add_grant(org: str, program: str, amount: str, deadline: str, url: str = ""):
    """Add new grant opportunity."""
    grants = load_grants()
    grant_id = f"{org.lower().replace(' ', '-')}-{len(grants)+1}"
    
    new_grant = {
        "id": grant_id,
        "org": org,
        "program": program,
        "amount": amount,
        "status": "research",
        "priority": "medium",
        "deadline": deadline,
        "submitted": None,
        "response": None,
        "notes": "",
        "url": url
    }
    
    grants.append(new_grant)
    save_grants(grants)
    return f"✅ Added: {org} — {program} ({amount})"


def print_usage():
    print("""
╔══════════════════════════════════════════════════════════════╗
║  🎯 Grant Command Center — Nova's Funding Tracker           ║
╚══════════════════════════════════════════════════════════════╝

Commands:
  grant-command.py status          # Show pipeline dashboard
  grant-command.py update <id> <status>  # Update grant status
  grant-command.py add <org> <program> <amount> <deadline> [url]
  grant-command.py next            # Show next high-priority action
  grant-command.py export          # Generate pipeline.md report

Examples:
  grant-command.py update w3f-open-1 submitted
  grant-command.py add "Polygon" "Village Grants" "$10K" "2025-03-01"

Status options: research, drafted, ready, submitted, approved, rejected
""")


def show_next_action(grants: List[Dict]):
    """Show the next high-priority action."""
    ready = [g for g in grants if g["status"] == "ready"]
    drafted = [g for g in grants if g["status"] == "drafted"]
    
    if ready:
        g = ready[0]
        print(f"""
╔══════════════════════════════════════════════════════════════╗
║  🚀 READY TO SUBMIT                                         ║
╚══════════════════════════════════════════════════════════════╝

  {g['org']} — {g['program']}
  💰 {g['amount']}
  📝 {g['notes']}
  🔗 {g['url']}

  Execute: Update status → "grant-command.py update {g['id']} submitted"
""")
    elif drafted:
        g = drafted[0]
        print(f"""
╔══════════════════════════════════════════════════════════════╗
║  📝 READY TO FINALIZE                                       ║
╚══════════════════════════════════════════════════════════════╝

  {g['org']} — {g['program']}
  💰 {g['amount']}
  📝 {g['notes']}
  🔗 {g['url']}

  Next: Finalize application and submit
""")
    else:
        print("""
╔══════════════════════════════════════════════════════════════╗
║  🔍 NO IMMEDIATE ACTIONS                                    ║
╚══════════════════════════════════════════════════════════════╝

  All high-priority grants in research phase.
  Consider:
  1. Draft W3F proposal (already done!)
  2. Research new opportunities
  3. Build portfolio for stronger applications
""")


def main():
    import sys
    
    if len(sys.argv) < 2:
        print_usage()
        sys.exit(1)
    
    command = sys.argv[1].lower()
    
    if command == "help" or command == "-h":
        print_usage()
        return
    
    grants = load_grants()
    
    if command == "status":
        print(generate_pipeline_report(grants))
    
    elif command == "export":
        report = generate_pipeline_report(grants)
        PIPELINE_FILE.parent.mkdir(parents=True, exist_ok=True)
        PIPELINE_FILE.write_text(report)
        print(f"✅ Exported to {PIPELINE_FILE}")
    
    elif command == "next":
        show_next_action(grants)
    
    elif command == "update":
        if len(sys.argv) < 4:
            print("Usage: grant-command.py update <grant_id> <status>")
            sys.exit(1)
        print(update_status(sys.argv[2], sys.argv[3]))
    
    elif command == "add":
        if len(sys.argv) < 6:
            print("Usage: grant-command.py add <org> <program> <amount> <deadline> [url]")
            sys.exit(1)
        url = sys.argv[6] if len(sys.argv) > 6 else ""
        print(add_grant(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], url))
    
    else:
        print(f"❌ Unknown command: {command}")
        print_usage()
        sys.exit(1)


if __name__ == "__main__":
    main()
