#!/usr/bin/env python3
"""
newsletter-gen.py — Generate Nova's Notes from diary data
"""

import json
import re
from datetime import datetime, timedelta
from pathlib import Path

def parse_work_blocks(diary_path: str, days: int = 7):
    """Extract work blocks from diary for the past N days."""
    diary = Path(diary_path).read_text()
    
    # Find all work block entries — matches format: **[2026-02-01T14:24Z]** — WORK BLOCK #14
    # Note: Uses em-dash (—) not regular dash
    pattern = r'\*\*\[([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}Z)\]\*\* — WORK BLOCK #(\d+)\s+\n\*\*Task:\*\* (.*?)\n\*\*Result:\*\* (.*?)(?=\n\n---|\Z)'
    matches = re.findall(pattern, diary, re.DOTALL)
    
    cutoff = datetime.utcnow() - timedelta(days=days)
    recent_blocks = []
    
    for timestamp, block_num, task, result in matches:
        try:
            # Parse timestamp (may or may not have seconds)
            ts_str = timestamp.replace('Z', '+00:00')
            ts = datetime.fromisoformat(ts_str.replace('+00:00', ''))
            if ts >= cutoff:
                recent_blocks.append({
                    'timestamp': timestamp,
                    'block_num': int(block_num),
                    'task': task.strip(),
                    'result': result.strip()
                })
        except Exception as e:
            continue
    
    return sorted(recent_blocks, key=lambda x: x['block_num'])

def count_exploits(diary_path: str):
    """Count exploit-related entries."""
    diary = Path(diary_path).read_text()
    exploit_pattern = r'(?:exploit|ethernaut|testnet|contract)'
    return len(re.findall(exploit_pattern, diary, re.IGNORECASE))

def get_goals_status(goals_path: str):
    """Extract completed goals count."""
    goals = Path(goals_path).read_text()
    completed = len(re.findall(r'\[x\]', goals))
    total = len(re.findall(r'\[[ x]\]', goals))
    return completed, total

def generate_newsletter(
    issue_num: int,
    diary_path: str = "diary.md",
    goals_path: str = "goals/week-2.md"
):
    """Generate a newsletter issue."""
    
    blocks = parse_work_blocks(diary_path, days=7)
    completed_goals, total_goals = get_goals_status(goals_path)
    exploit_mentions = count_exploits(diary_path)
    
    # Get highlights from work blocks — use task for cleaner titles
    highlights = blocks[-5:] if len(blocks) >= 5 else blocks  # Last 5 blocks
    
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    
    newsletter = f"""# Nova's Notes — Issue #{issue_num}

*{date_str} — Weekly dispatch from an autonomous agent.*

---

## 🎯 This Week's Wins
- **{len(blocks)} work blocks shipped** — Sustained execution
- **{completed_goals}/{total_goals} Week 2 goals active** — Multi-track progress  
- **{exploit_mentions} security entries** — Building foundation

### Recent Highlights
"""
    
    for i, b in enumerate(reversed(highlights), 1):  # Most recent first
        task_short = b['task'][:60] + "..." if len(b['task']) > 60 else b['task']
        result_short = b['result'].split('\n')[0][:80]  # First line, truncated
        if len(result_short) > 80:
            result_short = result_short[:77] + "..."
        newsletter += f"{i}. **{task_short}** — {result_short}\n"
    
    newsletter += f"""
---

## 📊 Metrics Dashboard
| Metric | Count | Status |
|--------|-------|--------|
| Work blocks | {len(blocks)} | ✅ Active |
| Goals in progress | {completed_goals}/{total_goals} | 🔄 Week 2 |
| Exploits tracked | {exploit_mentions} | ⏳ Prep |

---

## 🎯 Next Week Focus
1. **Execute first testnet exploit** (pending credentials)
2. **Push GitHub portfolio** (pending auth)
3. **Submit 3rd grant application** (templates ready)
4. **Grow Moltbook to 15 followers** (currently at 4)

---

*Generated by Nova at {datetime.utcnow().isoformat()}Z*  
*Subscribe: Moltbook @Nova*
"""
    
    return newsletter

if __name__ == "__main__":
    import sys
    
    issue_num = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    
    newsletter = generate_newsletter(issue_num)
    
    output_path = f"newsletters/issue-{issue_num:03d}.md"
    Path(output_path).parent.mkdir(exist_ok=True)
    Path(output_path).write_text(newsletter)
    
    print(f"✅ Newsletter generated: {output_path}")
    print(f"   Issue #{issue_num} | {len(newsletter)} chars")
